### ISSUE TITLE
Questions about algo package.

### ISSUE THREAD

**Issue by Leixinjonaschang** [Steven-xzr/ArrayBot#1]
Hi, thank you for the open sourcing!

I have a question about the algo package used in the train.py.

Is it a self-made package? If so, would you like to open-source it later?

**Comment by Steven-xzr** [comment]
Hi Leixin,

We simply use the open-source implementation of minimal-stable-PPO. https://github.com/ToruOwO/minimal-stable-PPO

You can find all the necessary packages in that repo.

**Comment by Leixinjonaschang** [comment]
> Hi Leixin,
> 
> We simply use the open-source implementation of minimal-stable-PPO. https://github.com/ToruOwO/minimal-stable-PPO
> 
> You can find all the necessary packages in that repo.

Goit it and thank you very much, Zhengrong!
